;  Copyright (C) 2002 Mason Kidd (mrkidd@mrkidd.com)
; 
;  This file is part of EmbedWeb.
; 
;  EmbedWeb is free software; you can redistribute it and/or modify
;  it under the terms of the GNU General Public License as published by
;  the Free Software Foundation; either version 2 of the License, or
;  (at your option) any later version.
; 
;  EmbedWeb is distributed in the hope that it will be useful,
;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;  GNU General Public License for more details.
; 
;  You should have received a copy of the GNU General Public License
;  along with EmbedWeb; if not, write to the Free Software
;  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA

; 80515 Processor Generic Port Bit Address Declarations

$SAVE
$NOLIST

; BIT Register
; P5
P5_0	bit		0f8h
P5_1	bit		0f9h
P5_2	bit		0fah
P5_3	bit		0fbh
P5_4	bit		0fch
P5_5	bit		0fdh
P5_6	bit		0feh
P5_7	bit		0ffh

; P4
P4_0	bit		0e8h
P4_1	bit		0e9h
P4_2	bit		0eah
P4_3	bit		0ebh
P4_4	bit		0ech
P4_5	bit		0edh
P4_6	bit		0eeh
P4_7	bit		0efh

$RESTORE

